// <auto-generated />
namespace EpamLibrary.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RBDb3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RBDb3));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091407328_RBDb3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
