// <auto-generated />
namespace EpamLibrary.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RBDb5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RBDb5));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091440378_RBDb5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
